name: Bike-point-extract

on: 
  schedule:
    - cron: '0 * * * *'  # Runs at the start of every hour (UTC)
  workflow_dispatch:

jobs:
  extract-and-upload:
    runs-on: ubuntu-latest
    environment: Bike Point Environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run extract script
        run: python output_json_api.py  

      - name: Upload data to S3
        env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}   
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}
          AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
        run: python s3_upload_api.py  
